### ISSUE TITLE
Remove CrowdStrike

### ISSUE THREAD

**Issue by apmunch** [SummitRoute/imdsv2_wall_of_shame#12]
IMDS v2 support added for CrowdStrike

**Comment by 0xdabbad00** [comment]
Is there any announcement or anything so I can confirm?  Otherwise I want to wait for either CrowdStrike or another customer to let me know.

**Comment by apmunch** [comment]
It's in release notes. See attached. 
<img width="1636" alt="Screen Shot 2022-04-06 at 11 42 00 AM" src="https://user-images.githubusercontent.com/7328483/162014143-61fffcd5-ef04-412f-9a92-0f5c74bb4251.png">

**Comment by 0xdabbad00** [comment]
Do they have a similar release notes for Linux? I've tried reaching out to Crowdstrike but have not received a response.

**Comment by apmunch** [comment]
Yes. 6.38.13501 Linux sensor supports IMDS v2.

**Comment by 0xdabbad00** [comment]
Awesome. I've removed Crowdstrike from the list.
