### ISSUE TITLE
Remove Databricks?

### ISSUE THREAD

**Issue by ghost** [SummitRoute/imdsv2_wall_of_shame#14]
Databricks now support IMDSv2 on workspaces, as described [here](https://docs.databricks.com/administration-guide/cloud-configurations/aws/imdsv2.html)! The feature is currently in [Public Preview](https://docs.databricks.com/release-notes/release-types.html) which means it can be enabled by all customers.

**Comment by 0xdabbad00** [comment]
Awesome! I've removed them from the list via https://github.com/SummitRoute/imdsv2_wall_of_shame/commit/7955e380e9516d569c7ba37176fc821ab0d1f6f9

**Comment by ghost** [comment]
Thanks!
