### ISSUE TITLE
Please update to F5 BIG-IP information, support added in VE 16.1.2.1

### ISSUE THREAD

**Issue by buulam** [SummitRoute/imdsv2_wall_of_shame#4]
Support for IMDSv2 was added to BIG-IP VE 16.1.2.1 - http://cdn.f5.com/product/bugtracker/ID968657.html

AWS configuration documentation - https://clouddocs.f5.com/cloud/public/v1/shared/aws-ha-IAM.html?highlight=imdsv2

Next release of 15.x (15.1.5.1) will include IMDSv2 support as well. Targeted for late March/early April.

https://support.f5.com/csp/article/K74004244 will be updated shortly

**Comment by 0xdabbad00** [comment]
Thank you. This is great to hear. I've removed F5 via https://github.com/SummitRoute/imdsv2_wall_of_shame/commit/527ce047ef306a15f55d81b778c68299b0d8769b
