### ISSUE TITLE
Remove Palo Alto?

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/imdsv2_wall_of_shame#5]
I was passed this link that Palo Alto now has support for IMDSv2
https://docs.paloaltonetworks.com/plugins/vm-series-and-panorama-plugins-release-notes/vm-series-plugin/vm-series-plugin-30/vm-series-plugin-300.html

It was confirmed that this now allows IMDSv2 support: https://twitter.com/vennemp/status/1499538666720567296

I do not know if there are still other PAN products that do not support IMDSv2, but if https://github.com/PaloAltoNetworks/AWS-GWLB-VMSeries/issues/25 is closed, then I will remove Palo Alto from my list.

I have not been able to get in touch with Palo Alto to confirm. My email to security@paloaltonetworks.com got an auto response that the email does not exist (which is another security issue in itself).  I do not use PAN products so I do not have a support or account rep to contact.

**Comment by maljb** [comment]
Finally, Yes! :)

But there are some limitation.
it's only supported above PAN-OS 10.2.0 version(need to upgrade from other version) and does not yet present on AWS marketplace.

**Comment by 0xdabbad00** [comment]
As long as there is a path forward for customers I'm going to be of the belief that this can now be removed, so I'll go ahead and do so.
