### ISSUE TITLE
Add Axonius

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/imdsv2_wall_of_shame#6]
I've received a report that this vendor should be added

**Comment by ctennis** [comment]
Here's a sample cloudtrail log indicating the failed request. The explicit deny comes from the instance policy denying all imdsv1 traffic (as noted, ec2RoleDelivery is "1.0")

![Screen Shot 2022-03-11 at 4 18 38 PM](https://user-images.githubusercontent.com/114/157969303-9354978a-78fb-4304-8adf-915005ac9969.png)

**Comment by ctennis** [comment]
Sample cloudtrail log indicating imdsv1 action in use (being denied by our policy)

![Screen Shot 2022-03-11 at 4 18 38 PM](https://user-images.githubusercontent.com/114/157971120-07a6e2d7-b37c-439f-9faf-39f774ace4c5.png)

**Comment by ctennis** [comment]
I worked with Axonius support today and they did confirm they have support for IMDSv2. There is a current issue in the product where if you have IMDSv1 and v2 enabled on an instance, but v1 usage blocked by SCP, the boto configuration they have doesn't work properly, and sounds like that is being fixed.

However, if you disable imdsv1 on the machine their services runs on, it will pick up and use IMDSv2 credentials correctly. So I suspect we can close this.

**Comment by 0xdabbad00** [comment]
I'd prefer not to close issues until they actually have their fix out, but it seems that as a customer you're happy with this, so I'm closing this out.
