### ISSUE TITLE
Add AWS Data Pipelines

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/imdsv2_wall_of_shame#8]
Should I keep this to vendors or also include AWS services? Pipelines is a managed service, so this seems reasonable to add.

**Comment by christophetd** [comment]
It's even worse if AWS own services don't support IMDSv2. I would definitely add it at the top of this list.

**Comment by 0xdabbad00** [comment]
Added in https://github.com/SummitRoute/imdsv2_wall_of_shame/commit/0d6fb563a37975702c84395e15feab26903d264e
